version: "3"

services:
  hadoop-slave1:
    image: sta/hadoop-cluster-base
    container_name: hadoop-slave1
    tty: true
  hadoop-slave2:
    image: sta/hadoop-cluster-base
    container_name: hadoop-slave2
    tty: true
  hadoop-master:
    image: sta/hadoop-cluster-master
    container_name: hadoop-master
    tty: true
    depends_on:
      - hadoop-slave1
      - hadoop-slave2
    links:
      - hadoop-slave1
      - hadoop-slave2
    ports:
    - 50070:50070
    - 8088:8088
    - 18080:18080
